# Site settings
title: RiskPlot Documentation
description: Professional risk visualization for Python
baseurl: "/riskplot"
url: "https://owendinsmore.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minimal

# GitHub Pages compatible plugins only
plugins:
  - jekyll-feed