# Site settings
title: RiskPlot Documentation
description: Professional risk visualization for Python
url: "https://owendinsmore.github.io"
baseurl: "/riskplot"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md